jat/urls.py
from django.urls import path
from . import views

app_name = 'jat'
urlpatterns = [
  path('', views.index, name='index'),
  path('new_app', views.new_app, name='new_app'),
  path('new_act', views.new_act, name='new_act'),
]

kvetchupapp/urls.py
from django.urls import path
from . import views

app_name = 'kvetchupapp'
urlpatterns = [
    path('kvetchup/', views.index, name='index'),
    path('kvetchup/reviews/', views.ratings, name="ratings"),
    path('kvetchup/profile/', views.profile, name="profile"),
    path('kvetchup/about/', views.about, name='about'),
    path('kvetchup/getSite/', views.getSite, name='getSite'),
    path('kvetchup/login/', views.login, name='login'),
    path('kvetchup/sendmail/', views.send, name='sendmail'),
    path('kvetchup/newreview/', views.new_review, name="newreview"),
    path('kvetchup/edit/', views.edit, name="edit"),
    path('kvetchup/editReview/', views.edit_review, name="edit_review"),
    path('kvetchup/deleteReview/', views.delete_review, name="delete_review")
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('kvetchup/', include('kvetchupapp.urls')),
    path('users/', include('users.urls')),
    path('jat/',include('jat.urls')),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
  path('', views.index, name='index'),
  path('projects/', views.projects, name='projects'),
  path('resume/', views.resume, name='resume'),
]

portfolio/models.py
from django.db import models

from users import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .helpers import captions
import os


# Create your views here.
def index(request):
    picture_files = []
    for filename in os.listdir('portfolio/static/portfolio/pictures'):
        url = 'portfolio/pictures/' + filename
        
        try:
            caption = captions.captions_dict[filename][0]
            idx = captions.captions_dict[filename][1]
        except KeyError:
            captions.captions_dict[filename] = [None, None]
            caption = None
            idx = None
        

        picture_files.append([url, caption, idx])

    picture_files.sort(key = lambda x: x[2])

    context = {
        "activate": "about",
        "pictures": picture_files,
    }
    
    return render(request, 'portfolio/index.html', context)

def projects(request):
    context = {
        "activate": "projects",
    }
    return render(request, 'portfolio/projects.html', context)

def resume(request):
    context = {
        "activate": "resume",
    }
    return render(request, 'portfolio/resume.html', context)

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dylan Lesniak</title>
    <!-- font -->
    <link href="https://fonts.googleapis.com/css2?family=Dorsa&family=Raleway:wght@300;400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <!-- css -->
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/style.css' %}">


    <!-- icons -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'portfolio/icons/favicon.ico' %}" type="image/x-icon"/>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'portfolio/icons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'portfolio/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'portfolio/icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'portfolio/icons/site.webmanifest' %}">

    <!-- vue.js -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    

</head>
<body>
    <div id="app">
    
        <!-- main header section -->
        <div class="navbar">
                <nav class="logo">
                    <p class="title">Dyl<span style="color:grey">a</span>n Lesni<span style="color:grey">a</span>k</p>
                    
                </nav>
            
            <nav class="menu_section">
                <a {% if activate == 'about' %}class="menu_links active"{% else %}class="menu_links"{% endif %} href="{% url 'portfolio:index' %}">About</a>
                <a {% if activate == 'projects' %}class="menu_links active"{% else %}class="menu_links"{% endif %} href="{% url 'portfolio:projects' %}">Projects</a>
                <a {% if activate == 'resume' %}class="menu_links active"{% else %}class="menu_links"{% endif %} href="{% url 'portfolio:resume' %}">Resume</a>
            </nav>
        
        </div>
        {% block content %}
        {% endblock %}   
    </div>
    <!-- js section -->
    <div class="bottom">
        <footer>
            <a class="project_links" href="mailto:mrdlesniak@gmail.com">MrDLesniak@gmail.com</a>
            <a class="project_links" href="https://github.com/mrdlesniak">MrDLesniak @ github</a>
            <a class="project_links" href="{% url 'portfolio:resume' %}">Resume</a>
        </footer>
    </div>

    <script type="text/javascript">
        var app = new Vue({
        el: '#app',
        delimiters: ['[[', ']]'],
        data: {
            toProject: false,
        },
        methods: {
            resetToProject: function () {
                if (this.toProject) {
                    this.toProject = false
                } else {
                    this.toProject = true
                }
            },
        }
        })

    // normal js
    var slideIndex = 1;
    var transishEnd = getTransitionEndEventName();

    // let's the vue load first so no conflicts
    setTimeout(() => {showDivs(slideIndex);}, 200);
    

    function plusDivs(n) {
        // if slide changes with a caption still up, this corrects that
        resetCaptions()

        showDivs(slideIndex += n);
    }

    // shows the picture and also sets the listeners for the shown picture
    function showDivs(n) {

        // variables
        var i;
        var slideDiv = document.getElementById("slideshow");
        var x = document.getElementsByClassName("gon_give_it_to_ya");
        var pics = document.getElementsByClassName("pic_slide");
        var captions = document.getElementsByClassName("caption_container");
        var more_infos = document.getElementsByClassName("more_info");
        
        // allows back arrow at start of slideshow
        if (n > pics.length) {slideIndex = 1};
        if (n < 1) {slideIndex = pics.length};

        // hides all slides (including current, but that's taken care of later)
        for (i = 0; i < pics.length; i++) {
            pics[i].style.display = "none"
        }

        // changes behavior on mobile
        if (screen.width < 1150) {
            showBar()
            addBarListeners()
            console.log("mobile")
        }
        else{
            addBarListeners()
            console.log("full screen")            
        }

        // shows current slide
        pics[slideIndex-1].style.display = "block"

    }

    // displays the part of the caption with "show more info"
    function showBar(wait = false) {
        var slideDiv = document.getElementById("slideshow");
        var pic = document.getElementsByClassName("pic_slide")[slideIndex-1];
        var caption = document.getElementsByClassName("caption_container")[slideIndex-1];
        var moreInfo = document.getElementsByClassName("more_info")[slideIndex-1];


        // transforms caption and text div up from bottom
        caption.classList.add("shown")
        moreInfo.classList.add("shown")

        // timeout prevents someone from mashing the click while full caption is closing
        

        console.log("showBar")
    }

    // hides the whole caption section. Including "show more info"
    function hideBar() {
        var caption = document.getElementsByClassName("caption_container")[slideIndex-1];
        var moreInfo = document.getElementsByClassName("more_info")[slideIndex-1];

        caption.classList.remove("shown")
        moreInfo.classList.remove("shown")

        console.log("hideBar")
    }

    // expands caption to full-size over the picture
    function expandCaption() {
        var caption = document.getElementsByClassName("caption_container")[slideIndex-1];
        var moreInfo = document.getElementsByClassName("more_info")[slideIndex-1];
        var text = document.getElementsByClassName("caption")[slideIndex-1];
        var x = document.getElementsByClassName("gon_give_it_to_ya")[slideIndex-1];

        removeBarListeners()
        removeCaptionContainerListeners()
        
        // expands to full size
        caption.style.transition = "1.3s"
        caption.style.animation = "fadeAllUp ease 1.3s"
        caption.style.height = "100%"
        caption.style.opacity = 0.8
        
        //  populates caption container
        moreInfo.style.display = "none"
        moreInfo.classList.remove("shown")
        // waits until caption is expanded 
        caption.addEventListener(transishEnd, moreInfoToBlock)
        
        x.classList.add("shown")
        text.classList.add("shown")
        
        
        console.log("expandCaption")
        waitForAddCaption()
    
    }

    // takes the fully expanded picture caption and sets it back to the default state
    function reduceCaption() {
        var caption = document.getElementsByClassName("caption_container")[slideIndex-1];
        var text = document.getElementsByClassName("caption")[slideIndex-1];
        var x = document.getElementsByClassName("gon_give_it_to_ya")[slideIndex-1];

        removeCaptionContainerListeners()

        caption.style.transition = "1.3s"
        caption.classList.remove("shown")
        x.classList.remove("shown")
        text.classList.remove("shown")
        
        caption.style.opacity = "0.6"
        caption.style.height = "30px"
        
        console.log("reduceCaption")    
        
        caption.addEventListener(transishEnd, waitForShowBar)
    }    
    
    // listeners and helpers

    function getTransitionEndEventName() {
        var transitions = {
            "transition"      : "transitionend",
            "OTransition"     : "oTransitionEnd",
            "MozTransition"   : "transitionend",
            "WebkitTransition": "webkitTransitionEnd"
        }
        let bodyStyle = document.body.style;
        for(let transition in transitions) {
            if(bodyStyle[transition] != undefined) {
                return transitions[transition];
            } 
        }
    }


    function addBarListeners() {
        var slideDiv = document.getElementById("slideshow");

        // needs the mouseover and off events for slideDive
        // needs click events for div to expandCaption
        // needs to have no other listeners available
        slideDiv.addEventListener("mouseover", showBar)
        slideDiv.addEventListener("mouseout", hideBar)
        slideDiv.addEventListener("click", expandCaption)
    }

    function removeBarListeners() {
        var slideDiv = document.getElementById("slideshow");
        
        slideDiv.removeEventListener("mouseover", showBar)
        slideDiv.removeEventListener("mouseout", hideBar)
        slideDiv.removeEventListener("click", expandCaption)
    }

    function addCaptionContainerListeners() {
        var slideDiv = document.getElementById("slideshow");

        slideDiv.addEventListener("click", reduceCaption)
    }

    function removeCaptionContainerListeners() {
        var slideDiv = document.getElementById("slideshow");

        slideDiv.removeEventListener("click", reduceCaption)
    }

    function resetCaptions() {
        var slideDiv = document.getElementById("slideshow");
        var caption = document.getElementsByClassName("caption_container")[slideIndex-1];
        var moreInfo = document.getElementsByClassName("more_info")[slideIndex-1];
        var text = document.getElementsByClassName("caption")[slideIndex-1];
        var x = document.getElementsByClassName("gon_give_it_to_ya")[slideIndex-1];

        removeBarListeners()
        removeCaptionContainerListeners()

        caption.style.opacity = "0.6"
        caption.style.height = "30px"
        moreInfo.style.display = "block"
        caption.classList.remove("shown")
        moreInfo.classList.remove("shown")
        x.classList.remove("shown")
        text.classList.remove("shown")


    }

    function moreInfoToBlock() {
        var caption = document.getElementsByClassName("caption_container")[slideIndex-1];
        var moreInfo = document.getElementsByClassName("more_info")[slideIndex-1];

        moreInfo.style.display = "block"
        caption.removeEventListener(transishEnd, moreInfoToBlock)
    }
    
    function waitForShowBar() {
        var caption = document.getElementsByClassName("caption_container")[slideIndex-1];
        

        console.log("waitForShowBar")
        addBarListeners()
        showBar()
        caption.style.transition = "0.5s"
        caption.removeEventListener(transishEnd, waitForShowBar)
    }
    
    function waitForAddCaption() {
        var caption = document.getElementsByClassName("caption_container")[slideIndex-1];
        
        console.log("waitForAddCaption")
        addCaptionContainerListeners()
        caption.removeEventListener(transishEnd, waitForAddCaption)
    }

    </script>

</body>
</html>

portfolio/templates/portfolio/index.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<div class="content">
    <div class="flexboxes">
        <h1>About me</h1>
    </div>
    <hr class="flexboxes h1hr">
    <br>
    
    <div class="flexboxes">
        <h3>I'm ready to work, and I'm ready to learn! I am currently located in Portland, Oregon.</h3>
    </div>
    <div class="about">
        <div class="text">
            <p class="about_text">
                <b>     I have over</b> 5 years' experience as a project manager and property director. I even have one year of experience as an English teacher in Japan!
                At the beginning of 2019 I made a big change in my life and began studying programming. I wanted something captivating where I could challenge myself and secure an opportunity to build towards the future. While I'm looking primarily for a backend role, I hope you can see from this website that I am passionate about every level of the stack. 
            </p>
    
            <p class="about_text">
                <b>When I'm not </b> working I like to sing, study Japanese, practice calligraphy, and play video games. I've even started cooking since lockdown began, which I think makes my mom very proud. I've lived in six cities in three different countries. 
            </p>
            
        </div>
        <div class="pic_container">
            <img id="dylan_pic" src="{% static 'portfolio/headshot/dylan_calray_bandw.jpg' %}" type="image/png">
            
        </div>
        
    </div>
    
    <div id="slideshow_section">
        <div>
            <h3 id="personal_experience">Now For a Personal Experience!</h3>
            <p id="personal_under"><b>To let you</b> see a little more about my hobbies and what I'm passionate about, please take a look at some of the photos I've accumulated through some of my adventures. <br> <br> <b> These will be </b> either cool pictures I've taken or pictures of things I'm passionate about! </p>

        </div>

        <div id="slides_and_buttons">
            
            <div id="slideshow">
                {% for picture, caption, index in pictures %}
                
                <img class="pic_slide" src="{% static picture %}" >
                
                {% if caption is not None %}
                <div class="caption_container">
                    <p class="more_info">Click for more information</p>
                    <p class="gon_give_it_to_ya">X</p>
                    <p class="caption">{{ caption|linebreaksbr }}</p>
                </div> 
                {% else %}
                <div class="caption_container">
                    <p class="more_info">{{caption}}</p>
                </div> 
                {% endif %}
                
                {% endfor %}
            </div>
            
            <div class="arrow_section">
                <button class="arrow_button left_arrow" onclick="plusDivs(-1)">&#10094;</button>
                <button class="arrow_button right_arrow" onclick="plusDivs(1)">&#10095;</button>

            </div>

        </div>
        
    </div>
    
    <h2 id="welcome">Welcome to my site!</h2>
</div>

{% endblock %}

portfolio/templates/portfolio/projects.html
{% extends 'portfolio/base.html' %}
{% block content %}
<div class="content">
    <!-- uses flexboxes to properly display the project slides -->
    <h1 class="flexboxes">Projects</h1>
    <hr class="flexboxes h1hr">

    <!-- each individual project slide -->
    <div class="project_box">
        <div class="project_area">
            <div class="project">
                <h1 ><a id="kvetchup" href="{% url 'kvetchupapp:index' %}">Kvetchup</a></h1>
                <p >Kvetchup is a simple app designed to help people complain to and rate certain companies.</p>
                <br>
                <p ><i> Python, Django, SQLite, Vue.js, Axios, HTML, CSS</i></p>
                <a class="project_links" href="https://github.com/mrdlesniak/mrdlesniak.github.io/tree/master/jat">source @ github</a>

            </div>
        </div>

        <div class="project_area">
            <div class="project">
                <h2 ><a id="jat" href="{% url 'jat:index' %}">Job Activity Tracker</a> </h2>
                <p >Site helps to organize activities. Groups them by week, and then by day.</p>
                <br>
                <p ><i> Python, Django, SQLite, Materialize, JavaScript, Vue.js, HTML, CSS</i></p>
                <a class="project_links" href="https://github.com/mrdlesniak/unemployment_organizer">source @ github</a>
            </div>
        </div>

        <div class="project_area">
            <div class="project">
               <h2> <a id="dl" v-on:click="resetToProject">Dyl<span style="color:grey">a</span>n Lesni<span style="color:grey">a</span>k.com</a> </h2>
                <p>My personal portfolio site.</p>
                <br>
                <p><i> Python, Django, SQLite, Vue.js, HTML, CSS, AWS Ec2, Nginx, Docker</i></p>
                <a class="project_links" href="https://github.com/mrdlesniak/mrdlesniak.github.io">source @ github</a>
            </div>
        </div>


    </div>

    <!-- modal from Dylan Lesniak slide -->
    <transition name="fade">
        <div v-if="toProject" class="modal_bg" v-on:click="resetToProject">
            <div class="to_project">
                <div class="project_modal_text">
                    <p id="to_project_title">Sorry bud, you're already here.</p>
                    <p>Check out my other projects though!</p>
                </div>
            </div>
        </div>
    </transition>
</div>
{% endblock %}

portfolio/templates/portfolio/resume.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}
<div class="content">
    <h2 class="resume_text">Download my resume <a class="project_links" href="{% static 'portfolio/dylan_lesniak_resume_2020.pdf' %}" download>here</a></h2>
    
    <div class="resume_icon_container">
        <a class="resume_icon" href="{% static 'portfolio/dylan_lesniak_resume_2020.pdf' %}" download>
            <img class="dl_button" src="{% static 'portfolio/icons/resume.png' %}" type="image/png"
                v-on:click="resetToProject"></img>
        </a>

    </div>
</div>

{% endblock %}