jat/urls.py
from django.urls import path
from . import views

app_name = 'jat'
urlpatterns = [
  path('', views.index, name='index'),
  path('new_app', views.new_app, name='new_app'),
  path('new_act', views.new_act, name='new_act'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('kvetchup/', include('kvetchupapp.urls')),
    path('users/', include('users.urls')),
    path('jat/',include('jat.urls')),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
  path('', views.index, name='index'),
  path('projects/', views.projects, name='projects'),
  path('resume/', views.resume, name='resume'),
]

jat/models.py
from django.db import models
import datetime

# Create your models here.
class Week(models.Model):
    week = models.CharField(max_length=200)
    year = models.CharField(max_length=200)

    #gets the first day of the week (usually sunday)
    def week_beginning(self):
        start_and_end_of_week = self.get_start_and_end_date_from_calendar_week(self.year, self.week)
        week_beginning = start_and_end_of_week[0].strftime('%m/%d/%Y')
        return week_beginning

    #gets the last day of the week (usually saturday)
    def week_end(self):
        start_and_end_of_week = self.get_start_and_end_date_from_calendar_week(self.year, self.week)
        week_end = start_and_end_of_week[1].strftime('%m/%d/%Y')
        return week_end

    #this function allows you to give a year and a week num and return the sunday and sunday of that week
    def get_start_and_end_date_from_calendar_week(self, year, calendar_week):
        sunday = datetime.datetime.strptime(f'{year}-{calendar_week}-0', "%Y-%W-%w").date()
        return sunday, sunday + datetime.timedelta(days=6.9)

    def __str__(self):
        return f"{self.week_beginning()} - {self.week_end()}"


class Date(models.Model):
    week = models.ForeignKey(Week, on_delete=models.PROTECT, related_name="dates")
    date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.date.strftime("%m/%d/%Y")

class Application(models.Model):
    #date, company name, location, contact method, type of work sought, results (so dumb)
    date = models.ForeignKey(Date, on_delete=models.PROTECT, related_name="applications")
    company_name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    contact_method = models.CharField(max_length=200)
    work_type = models.CharField(max_length=200)
    results = models.CharField(max_length=200) #hired or not hired

    def __str__(self):
        return self.company_name

class Activity(models.Model):
    date = models.ForeignKey(Date, on_delete=models.PROTECT, related_name="activities")
    activity = models.CharField(max_length=200)

    def __str__(self):
        return self.activity

jat/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from .models import Date, Application, Activity, Week
import datetime
import calendar 
from datetime import timedelta


# Create your views here.
def index(request):
    all_dates = Date.objects.order_by("-date")
    all_applications = Application.objects.order_by("company_name")
    all_activities = Activity.objects.all()
    all_weeks = Week.objects.order_by("-year", "-week")

    context = {
        "all_dates": all_dates,
        "all_applications": all_applications,
        "all_activities": all_activities,
        "all_weeks": all_weeks,
    }

    return render(request, 'jat/index.html', context)

#takes new application from form in html and saves it
#redirects back to homescreen
def new_app(request):
    new_app_date = request.POST['new_app_date']
    new_app_date = datetime.datetime.strptime(new_app_date, '%Y-%m-%d').date()

    date_exists = check_date(new_app_date)

    if date_exists:
        new_app_date = Date.objects.get(date=new_app_date)
    else:
        week = new_app_date.strftime("%V")
        year = str(new_app_date.year)
        if int(week) -2 >= 0:
            week = str(int(week) -2) #Datetime goes ahead by at least one week since Jan 1 is rarely sunday.  
        elif int(week) -2 < 0: 
            week = "51"
            year = str(int(year) - 1)
        #makes sure years aren't in a range that will break the database
        if int(year) > 9999:
            year = "9999"
        elif int(year) < 1000:
            year = "1000"
        week = save_new_week(week, year)
        new_date = Date(week=week, date=new_app_date)
        new_date.save()
        new_app_date = new_date

    new_app_co_name = request.POST['new_app_co_name']
    new_app_location = request.POST['new_app_location']
    new_app_contact_method = request.POST['new_app_contact_method']
    new_app_work_type = request.POST['new_app_work_type']
    new_app_results = request.POST['new_app_results']

    application = Application(date=new_app_date, company_name=new_app_co_name, location=new_app_location, contact_method=new_app_contact_method, work_type=new_app_work_type, results=new_app_results)
    application.save()

    return HttpResponseRedirect(reverse('jat:index'))


#takes new activity from form in html and saves it
#redirects back to homescreen
def new_act(request):
    new_act_date = request.POST['new_act_date']
    new_act_date = datetime.datetime.strptime(new_act_date, '%Y-%m-%d').date()

    date_exists = check_date(new_act_date)
    # checks if date exists. If it does, use the existing date object. 
    #If not, create one. 
    if date_exists:
        new_act_date = Date.objects.get(date=new_act_date)
    else:
        week = new_act_date.strftime("%V")
        year = str(new_act_date.year)
        if int(week) -2 >= 0:
            week = str(int(week) -2) #Datetime goes ahead by at least one week since Jan 1 is rarely sunday.  
        elif int(week) -2 < 0: 
            week = "51"
            year = str(int(year) - 1)
        #makes sure years aren't in a range that will break the database
        if int(year) > 9999:
            year = "9999"
        elif int(year) < 1000:
            year = "1000"
        week = save_new_week(week, year)
        new_date = Date(week=week, date=new_act_date)
        new_date.save()
        new_act_date = new_date
    
    new_activity = request.POST['new_activity']
    
    activity = Activity(date=new_act_date, activity=new_activity)
    activity.save()
    
    return HttpResponseRedirect(reverse('jat:index'))

#just checks if this date exists already
def check_date(new_act_date):
    all_dates = Date.objects.all()

    for date in all_dates:
        if date.date == new_act_date:
            return True
    return False

# tries to grab a week object. If it can't, it creates one.
# uses imported django exceptions. 
def save_new_week(week, year):
    try:
        week_obj = Week.objects.get(week=week, year=year)
        return week_obj
    except ObjectDoesNotExist:
        new_week = Week(week=week, year=year)
        new_week.save()
        return new_week
    except MultipleObjectsReturned:
        raise Exception("Multiple weeks. Oh no.")
    except:
        print("If try succeeds, then it escapes. If it doesn't, it should get to DoesNotExist every time. I don't know how we got here, but let's get to work! ")
        raise Exception("Bad Ending")


    

jat/templates/jat/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JAT</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- icon -->
    <link rel="shortcut icon" href="{% static 'jat/icons/favicon.ico' %}" type="image/x-icon">
    
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dorsa&family=Raleway:wght@300;400&display=swap" rel="stylesheet">

    <!-- css -->
    <link rel="stylesheet" type="text/css" href="{% static 'jat/style.css' %}" />

</head>
<body>
    <!-- navbar section -->
    <nav>
        <div class="nav-wrapper teal darken-4">
            <span class="logo">Job Activity Tracker</span>
        </div>
    </nav>

    <div class="content" id="app">
        <!-- section to add activity -->   
        <button class="waves-effect waves-light teal lighten-2 btn" v-on:click="showHideEvent">[[show_select]]</button>
            <!-- select form type -->
            <div class="input-field" v-show="show_select != 'Create Event'">
                <select v-model="application_or_activity"> 
                    <option value="" disabled selected>Choose Event</option>
                    <option value="activity">Activity</option>
                    <option value="application">Application</option>
                </select>
            </div>
                <!-- activity form -->
                <div id="activity_form" v-show="application_or_activity == 'activity' && show_select != 'Create Event'">
                    <form action="{% url 'jat:new_act' %}" method="post">
                        {% csrf_token %}
                        <input type="text" name="new_act_date" class="datepicker" placeholder="Date" required>
                        <!-- <input type="date" name="new_act_date" id="" required> -->
                        <input type="text" name="new_activity" placeholder="Activity Description" required>
                        <button class="teal lighten-2 btn">Submit</button>
                    </form>
                </div>

                <!-- application form -->
                <div id="application_form" v-show="application_or_activity == 'application' && show_select != 'Create Event'">
                    <form action="{% url 'jat:new_app' %}" method="post">
                        {% csrf_token %}
                        <input type="text" name="new_app_date" class="datepicker" placeholder="Date" required>
                        <!-- <input type="date" name="new_app_date" id="" required> -->
                        <input type="text" name="new_app_co_name" placeholder="Company" required>
                        <input type="text" name="new_app_location" placeholder="Location" required>
                        <input type="text" name="new_app_contact_method" placeholder="Contact Method" required>
                        <input type="text" name="new_app_work_type" placeholder="Work Type" required>
                        <input type="text" name="new_app_results" placeholder="Results" required>
                        <button class="teal lighten-2 btn">Submit</button>
                    </form>
                </div>

        <!-- collapsible dates -->
        <ul class="collapsible collapsible-accordion">
            {% for week in all_weeks %}

                <li>
                    <div class="collapsible-header center-align">{{week.week_beginning}} &mdash; {{week.week_end}}</div>
                        {% for date in week.dates.all %}
                            {% for application in date.applications.all %}
                                <div class="collapsible-body">
                                    <b>{{date}} : Application</b>  {{application}} | {{application.location}} | {{application.contact_method}} | {{application.work_type}} | {{application.results}}
                                </div>
                            {% endfor %}
                            {% for activity in date.activities.all %}
                            <div class="collapsible-body">
                                <b>{{date}} : Activity</b> {{activity}}
                            </div>
                            {% endfor %}
                        {% endfor %}
                </li>
        
            {% endfor %}

        </ul>
        
        <!-- profile logo -->
        <img class="dl_button" src="{% static 'portfolio/icons/favicon-white.ico' %}" type="image/png"
            v-on:click="resetToProject"></img>

        <!-- modal back to profile projects page -->
        <transition name="fade">
            <div v-if="toProject" class="modal_bg" v-on:click="resetToProject">
                <div class="to_project">
                    <div class="project_modal_text">
                        <p id="to_project_title">Would you like to return to the DL Projects page?</p>
                        <div class="modal_buttons">
                            <a class="to_project_text" href="{% url 'portfolio:projects' %}">Yes</a>
                            <a class="to_project_text">No</a>
                        </div>
                    </div>
                </div>
            </div>
        </transition>
    </div>

    <!-- JS Section -->
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- Vue -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script>
        // accordion
        document.addEventListener('DOMContentLoaded', function () {
                var elems = document.querySelectorAll('.collapsible');
                var instances = M.Collapsible.init(elems);
            });
        
        document.addEventListener('DOMContentLoaded', function () {
                var elems = document.querySelectorAll('select');
                var instances = M.FormSelect.init(elems);
            });

        // date picker
        document.addEventListener('DOMContentLoaded', function () {
                var elems = document.querySelectorAll('.datepicker');
                var instances = M.Datepicker.init(elems, {
                    format:"2020-mm-dd", 
                    autoClose: true,
                    min: new Date(1000, 0, 1),
                    max: new Date(3000, 0, 1)});
            });

        let app = new Vue({
                el: '#app',
                delimiters: ['[[', ']]'],
                data: {
                    show_select: "Create Event",
                    application_or_activity: "", 
                    toProject: false,
                },
                methods: {
                    showHideEvent: function () {
                        if (this.show_select === "Create Event") {
                            this.show_select = "Hide Event Creator"
                        } else {
                            this.show_select = "Create Event"
                            this.application_or_activity = ""
                        }
                    },  
                    resetToProject: function () {
                        if (this.toProject) {
                            this.toProject = false
                        } else {
                            this.toProject = true
                        }
                    },
                }
            })
    </script>
</body>
</html>