jat/urls.py
from django.urls import path
from . import views

app_name = 'jat'
urlpatterns = [
  path('', views.index, name='index'),
  path('new_app', views.new_app, name='new_app'),
  path('new_act', views.new_act, name='new_act'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('kvetchup/', include('kvetchupapp.urls')),
    path('users/', include('users.urls')),
    path('jat/',include('jat.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login_page, name='login'),
    path('login_user/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('register_user/', views.register_user, name='register_user'),
    path('logout/', views.logout_user, name='logout')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    phone = models.CharField(max_length=20, null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to='profile_images/', null=True, blank=True)
    verified = models.BooleanField(default=False)


    def __str__(self):
        return self.username

users/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.decorators import login_required
from kvetchupapp import models
from users.models import User

import requests


def register(request):
    message = request.GET.get('message', '')
    context = {
        'message': message
    }
    return render(request, 'users/register.html', context)

def register_user(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']

    if User.objects.filter(username=username).exists():
        return HttpResponseRedirect(reverse('users:register') + '?message=exists')

    user = User.objects.create_user(username, email, password)
    login(request, user)

    return HttpResponseRedirect(reverse('kvetchupapp:index'))


def login_page(request):
    message = request.GET.get('message', '')
    next = request.GET.get('next', '')
    context = {
        'next': next,
        'message': message
    }
    return render(request, 'users/login.html', context)


def login_user(request):

    next = request.POST['next']

    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        if next != '':
            return HttpResponseRedirect(next)
        return HttpResponseRedirect(reverse('kvetchupapp:index'))
    if next == '':
        return HttpResponseRedirect(reverse('users:login') + '?message=failure')
    return HttpResponseRedirect(reverse('users:login') + '?message=failure&next='+next)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('kvetchupapp:index') + '?message=True')

@login_required
def home(request):
    return render(request, 'users/home.html')

users/templates/users/login.html
{% extends 'kvetchupapp/base.html' %}

{% block content %}
<div class="content">
    {% if message == 'failure' %}
    <h3 style="color:red">That username and password do not match</h3>
    {% elif message == 'loggedout' %}
    <h3 style="color:blue">Successfully logged out</h3>
    {% endif %}
    <h1>Login</h1>
    <form action="{% url 'users:login_user' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}"/>
        <input type="text" name="username" value="" placeholder="username">
        <input type="password" name="password" value="" placeholder="password">
        <button type="submit">Login</button>
    </form>
    <a class="inline_link" href="{% url 'users:register' %}">Register</a>

</div>
{% endblock %}

users/templates/users/register.html
{% extends 'kvetchupapp/base.html' %}

{% block content %}
<div class="content">
    {% if message == 'exists' %}
        <h3 style="color:red">Username already exists.</h3>
    {% endif %}
    <h1>Register</h1>
    <form action="{% url 'users:register_user' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" value="" placeholder="Username" required>
        <input type="email" name="email" value="" placeholder="Email" required>
        <input type="password" name="password" value="" placeholder="Password" required>
        <button type="submit">Register</button>
    </form>
    <a class="inline_link" href="{% url 'users:login' %}">Login</a>

</div>
{% endblock %}