jat/urls.py
from django.urls import path
from . import views

app_name = 'jat'
urlpatterns = [
  path('', views.index, name='index'),
  path('new_app', views.new_app, name='new_app'),
  path('new_act', views.new_act, name='new_act'),
]

kvetchupapp/urls.py
from django.urls import path
from . import views

app_name = 'kvetchupapp'
urlpatterns = [
    path('kvetchup/', views.index, name='index'),
    path('kvetchup/reviews/', views.ratings, name="ratings"),
    path('kvetchup/profile/', views.profile, name="profile"),
    path('kvetchup/about/', views.about, name='about'),
    path('kvetchup/getSite/', views.getSite, name='getSite'),
    path('kvetchup/login/', views.login, name='login'),
    path('kvetchup/sendmail/', views.send, name='sendmail'),
    path('kvetchup/newreview/', views.new_review, name="newreview"),
    path('kvetchup/edit/', views.edit, name="edit"),
    path('kvetchup/editReview/', views.edit_review, name="edit_review"),
    path('kvetchup/deleteReview/', views.delete_review, name="delete_review")
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('kvetchup/', include('kvetchupapp.urls')),
    path('users/', include('users.urls')),
    path('jat/',include('jat.urls')),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
  path('', views.index, name='index'),
  path('projects/', views.projects, name='projects'),
  path('resume/', views.resume, name='resume'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login_page, name='login'),
    path('login_user/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('register_user/', views.register_user, name='register_user'),
    path('logout/', views.logout_user, name='logout')
]

kvetchupapp/models.py
from django.db import models

from django.utils import timezone
from datetime import datetime

from users.models import User



class Site(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField(max_length=200)
    phone_number = models.CharField(max_length=200, default="xxx-xxx-xxxx")
    customer_support_page = models.URLField(max_length=200, default="", blank=True)
    email = models.EmailField(max_length=254, default="", blank=True)
    #each site can have many reviews from many users. 
    #users can have many reviews to many sites.
    #reviews can have only one user and only one site. 

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f"Name: {self.name} | Id: {self.id}"

class Review(models.Model):
    review = models.TextField(blank=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, related_name="reviews")
    site = models.ForeignKey(Site, on_delete=models.PROTECT, null=True, blank=True, related_name="reviews") 
    review_date = models.DateTimeField(default=datetime.now, blank=True)

    class Meta:
        ordering = ['-review_date']

    def __str__(self):
        return self.review

kvetchupapp/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from . import models
import json
import random
import string

# Create your views here.
def index(request):
    sites = models.Site.objects.order_by('name')
    message = request.GET.get('message', False)
    context = {
        "sites": sites,
        "message": message,
    }
    return render(request, 'kvetchupapp/index.html', context)  

def getSite(request): 
    siteId = request.GET.get("siteId", "error")
    if siteId == "error":
        return JsonResponse({"site": "NO SITE FOUND"})
    site = models.Site.objects.get(id=siteId)
    queryset_reviews = list(site.reviews.values()) #returns a valuequeryset. list() makes it a list of dictionaries of the reviews.
    
    for i in range(len(queryset_reviews)):
        review = queryset_reviews[i]
        review["user_id"] = str(models.User.objects.get(id=review["user_id"])) #replaces user_id with the actual user
        review["user"] = review.pop("user_id")
        #stores username 

        review['review_date'] = review['review_date'].strftime("%m/%d/%Y, %H:%M:%S")

    data = {
        "name": site.name,
        "url": site.url,
        "email": site.email,
        "phone_number": site.phone_number,
        "reviews":  queryset_reviews,
        }

    return JsonResponse({"site":data})

def formatted_phone(phone_number):
    formatted_num = ""
    for i in range(len(phone_number)):
        formatted_num += phone_number[i]
        if i == 2 or i == 5:
            formatted_num += "-"
    return formatted_num

def ratings(request):
    sites = models.Site.objects.order_by('name')
    message = request.GET.get('message', False)
    context = {
        "sites": sites,
        "message": message,
    }
    for site in sites:
        print(site.reviews)
        break
    return render(request, 'kvetchupapp/ratings.html', context) 

@login_required
def login(request):
    sites = models.Site.objects.order_by('name')
    context = {
        "sites": sites,
    }
    return render(request, 'kvetchupapp/index.html', context) 

#this method will be in charge of sending the confirmation email to verify accounts. 
def send(request):
    # send_mail(, 'mrdlesniak@gmail.com', ['mrdlesniak@gmail.com'], fail_silently=False)
    return HttpResponseRedirect(reverse('kvetchupapp:index'))

@login_required
def new_review(request):
    review_text = request.POST['review_text']
    user = request.user
    site_id = request.POST['siteId']
    site = models.Site.objects.get(id=site_id)
    review = models.Review(review=review_text, user=user, site=site )
    review.save()
    
    return HttpResponseRedirect(reverse('kvetchupapp:ratings') + '?message=True')

@login_required
def profile(request):
    message = request.GET.get('message', '')
    return render(request, 'kvetchupapp/profile.html', {'message':message})

@login_required
def edit(request):
    #get user 
    #set each value of the user instance to the new values from the edit. 
    #save
    message = "True"

    context = {
        'message': message
    }
    user = request.user
    username = request.POST['user_name']
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']

    if models.User.objects.filter(username=username).exists() and user.username != username:
        return HttpResponseRedirect(reverse('kvetchupapp:profile') + '?message=exists')
    if username:
        user.username = username
    if first_name:
        user.first_name = first_name
    if last_name:
        user.last_name = last_name
    
    user.save()

    return HttpResponseRedirect(reverse('kvetchupapp:profile') + '?message=True') 

@login_required
def edit_review(request): 
    new_review_txt = request.POST['review']
    review_id = request.POST['review_id']
    review_obj = models.Review.objects.get(id=review_id)
    review_obj.review = new_review_txt
    review_obj.save()
    print(review_obj.review)

    return HttpResponseRedirect(reverse('kvetchupapp:profile') + '?message=True') 

@login_required
def delete_review(request):

    review_id = request.POST['review_id']
    print("review_id" + review_id + ".")
    review = models.Review.objects.get(id=review_id)
    review.delete()

    return HttpResponseRedirect(reverse('kvetchupapp:profile') + '?message=deleted')

def about(request):
    return render(request, 'kvetchupapp/about.html')

kvetchupapp/templates/kvetchupapp/about.html
{% extends 'kvetchupapp/base.html' %}

{% block content %}
<div class="content">
    <h2>About</h2>

    <p class="about">This site was created as a way to assist people complaining, or kvetching. It is often very difficult and time-consuming to find the customer service information when you are using a site. With Kvetchup, that becomes a little easier. The site is designed to be simple and effective. It gives you all the information you need while still maintaining a minimalist aesthetic.  </p><br>
    <p> Don't like it? Send us an email or leave us a review. </p> <br>
    <p> Thanks for using Kvetchup,</p> <br>
    
    <div class="profile_fields">
        <div class="ceo">Dylan Lesniak, Kvetchup CEO</div>
        
        <div class="email" >
            <div>Email Address: &ensp; info.kvetchup@gmail.com</div>
        </div>
    
        {% if user.is_anonymous  %}
        <div class="login_message" v-if="name">
            <span class="login_notice">Please <a class="inline_link" href="{% url 'users:login' %}">log in</a> to send
                emails.</span>
        </div>
        {% endif %}
    </div>

</div>


{% endblock %}

kvetchupapp/templates/kvetchupapp/base.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Myeongjo&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dorsa&family=Raleway:wght@300;400&display=swap" rel="stylesheet">
    <!-- icon -->
    <link rel="shortcut icon" href="{% static 'kvetchupapp/icons/favicon.ico' %}" type="image/x-icon">

    <!-- Vue -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <!-- Axios -->
    <script type="text/javascript" src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <!-- css -->
    <link rel="stylesheet" type="text/css" href="{% static 'kvetchupapp/style.css' %}" />

    <title>Kvetchup</title>
</head>
<body>
    <div id="app">
        <div id="header_body">
            <header>
                <div class="hamburger_icon" v-on:click="showHide">
                    <div class="ham_line"></div>
                    <div class="ham_line"></div>
                    <div class="ham_line"></div>
                </div>
                <div class="title">
                    <h1><a href="{% url 'kvetchupapp:index' %}" class="h1a"> Kvetchup</a></h1>
                    <span class="subtitle">For when you need to up your kvetching game.</span>
                </div>
                <div class="login_logout">
                    {% if user.is_authenticated %}
                        <a class="inline_link" href="{% url 'users:logout' %}">Logout</a>
                    {% else %}
                        <a class="inline_link" href="{% url 'users:login' %}">Login</a>
                        {% if message == 'True' %}
                            <transition name="fade">
                                <a class="modal_bg" href="{% url 'kvetchupapp:index' %}">
                                    <div class="modal">
                                        <div class="modal_text">You Have Successfully</div>
                                        <div class="modal_text">Logged Out</div>
                                    </div>
                                </a>
                            </transition>
                        {% endif %}
                    {% endif %}
                </div>
            </header>
            <hr>
            <transition name="fade">
                <div class="menu" v-show="show">
                    <a class="tablinks" href="{% url 'kvetchupapp:index' %}">Home</a>
                    <a class="tablinks" href="{% url 'kvetchupapp:profile' %}">Profile</a>
                    <a class="tablinks" href="{% url 'kvetchupapp:ratings' %}">Reviews</a>
                    <a class="tablinks" href="{% url 'kvetchupapp:about' %}">About</a>
                </div>
            </transition>
            {% block content %}
            {% endblock %}
        </div>
        <div class="bottom">
            <hr />
            <footer>
                <!-- profile logo -->
                <img class="dl_button" src="{% static 'portfolio/icons/favicon-white.ico' %}" type="image/png" v-on:click="resetToProject"></img>

                <!-- modal to bring user back to profile projects page -->
                <transition name="fade">
                    <div v-if="toProject" class="modal_bg" v-on:click="resetToProject">
                        <div class="to_project">
                            <div class="project_modal_text">
                                <p id="to_project_title">Would you like to return to the DL Projects page?</p>
                                <div class="modal_buttons">
                                    <a class="to_project_text" href="{% url 'portfolio:projects' %}">Yes</a>
                                    <a class="to_project_text" >No</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </transition>

                (c) Dylan Lesniak 2020
            </footer>
        </div>
    </div>
    <script type="text/javascript">
        let app = new Vue({
            el: '#app',
            delimiters: ['[[', ']]'],
            data: {
                siteId: "",
                name: "",
                url: "",
                email: "",
                customer_support_site: "",
                phone_number: "",
                review: "",
                reviews: "",
                reviewNum: "",
                userName: "{{user.username}}",
                firstName: "{{user.first_name}}",
                lastName: "{{user.last_name}}",
                max_height: "0px",
                show: false,
                hide: 'Show',
                logged_in: false,
                show_logged_in: false,
                modal: false,
                edit_user: true,
                isSure: false,
                isSureReview: false,
                isSureDelete: false,
                isValid: true,
                usrnmError: false,
                frstnmError: false,
                lstnmError: false,
                toProject: false,
            },
            methods: {
                getSiteView: function () {
                    if (this.siteId == "") {
                        return
                    }
                    axios({
                        method: 'get',
                        url: '{% url "kvetchupapp:getSite" %}',
                        params: {
                            siteId: this.siteId
                        }
                    }).then(response => {
                        let siteObj = response.data.site
                        this.name = siteObj.name
                        this.url = siteObj.url
                        this.email = siteObj.email
                        this.phone_number = siteObj.phone_number
                        this.reviews = siteObj.reviews
                    })
                },
                showHide: function () {
                    if (this.show) {
                        this.max_height = "0px"
                        this.show = false
                    } else {
                        this.max_height = "null"
                        this.show = true
                    }
                },
                notLoggedIn: function () {
                    if (this.logged_in) {
                        return
                    } else {
                        this.show_logged_in = true
                    }
                    
                },
                showModal: function () {
                    this.modal = true
                },
                displayAdditional: function () {
                    if (this.hide == 'Hide') {
                        this.hide = 'Show'
                    } else {
                        this.hide = 'Hide'
                    }
                },
                editUserFunction: function () {
                    if (this.edit_user){
                        this.edit_user = false
                    } else {
                        this.edit_user = true
                    }
                },
                checkValues: function () {
                    this.usrnmError = false
                    this.frstnmError = false
                    this.lstnmError = false

                    this.checkUsrNm()
                    this.checkFrstNm()
                    this.checkLstNm()

                    if (this.usrnmError || this.frstnmError || this.lstnmError) {
                        this.isValid = false
                        return 
                    }


                    if (this.isSure) {
                        this.isSure = false
                    } else {
                        this.isSure = true
                    }
                },
                checkUsrNm: function () {
                    
                    let acceptable_str = "@.+-_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890"

                    for (let i = 0; i < this.userName.length; ++i) {
                        if (!(acceptable_str.includes(this.userName[i]))) {

                            this.usrnmError = true
                            return
                        }
                    }
                },
                checkFrstNm: function () {
                    let acceptable_str = "@.+-_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890"

                    for (let i = 0; i < this.firstName.length; ++i) {
                        if (!(acceptable_str.includes(this.firstName[i]))) {

                            this.frstnmError = true
                            return
                        }
                    }
                },
                checkLstNm: function() {
                    let acceptable_str = "@.+-_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890"

                    for (let i = 0; i < this.lastName.length; ++i) {
                        if (!(acceptable_str.includes(this.lastName[i]))) {

                            this.lstnmError = true
                            return
                        }
                    }
                },
                checkReview: function () {
                    if (this.isSureReview) {
                        this.isSureReview = false
                    } else {
                        this.isSureReview = true
                    }
                },
                showDeleteModal: function () {
                    if (this.isSureDelete == false) {
                        this.isSureDelete = true
                    } else {
                        this.isSureDelete = false
                    }
                },
                resetValid: function () {
                    
                    if (this.isValid) {
                        this.isValid = false
                    } else {
                        this.isValid = true
                    }
                },
                resetisSure: function () {
                    this.isSure = false
                },
                resetisSureReview: function () {
                    this.isSureReview = false
                },
                resetisSureDelete: function () {
                    this.isSureDelete = false
                },
                resetToProject: function () {
                    if (this.toProject) {
                        this.toProject = false
                    } else {
                        this.toProject = true
                    }
                },
            }
        })
    </script>
</body>

kvetchupapp/templates/kvetchupapp/profile.html
{% extends 'kvetchupapp/base.html' %}

{% block content %}
<div class="content">
    <!-- modal for after editing -->
    {% if message == 'True' %}
        <transition name="fade">
            <a class="modal_bg" href="{% url 'kvetchupapp:profile' %}">
                <div class="modal">
                    <div class="modal_text">Profile Edited Successfully</div>
                </div>
            </a>
        </transition>
    {% endif %}

    <!-- modal for if user edits username to one that already exists -->
    {% if message == 'exists' %}
        <transition name="fade">
            <a class="modal_bg" href="{% url 'kvetchupapp:profile' %}">
                <div class="modal">
                    <div class="modal_text">Username Already Exists</div>
                    <div class="modal_text">Please Try Again</div>
                </div>
            </a>
        </transition>
    {% endif %}

    <!-- modal for if user deleted a review -->
    {% if message == 'deleted' %}
        <transition name="fade">
            <a class="modal_bg" href="{% url 'kvetchupapp:profile' %}">
                <div class="modal">
                    <div class="modal_text">Review Was </div>
                    <div class="modal_text">Successfully Deleted</div>
                </div>
            </a>
        </transition>
    {% endif %}

    <!-- display of user information -->
    <h2>Profile</h2>
    <div class="welcome">Welcome, {{user.username | title}}</div>
    <div v-if="!edit_user" class="requirements">Do not include spaces</div>
    <div class="profile_fields">
        <form method="post" action="{% url 'kvetchupapp:edit' %}" class="profile_form" v-on:keydown.enter.prevent="checkValues">
            {% csrf_token %}
            
            <!-- username. Checks for invalid entries -->
            <div class="profile_username">
                <span v-if="edit_user">Username: &ensp; {{user.username | title}}</span>
                <span v-bind:class="{error: usrnmError}" v-if="!edit_user">Username: &ensp; {{user.username | title}}<input type="text" name="user_name" v-model="userName" ></span>
                <div v-if="!edit_user" class="requirements">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</div>
            </div>
            <!-- self-explanatory sections. Can be edited. Checks for errors. -->
            <div class="first_name">
                <span v-if="edit_user">First Name: &ensp; {{user.first_name}}</span>
                <span v-bind:class="{error: frstnmError}" v-if="!edit_user">First Name: &ensp; {{user.first_name}}<input type="text" name="first_name" v-model="firstName"></span>
            </div>
            <div>
                <span v-if="edit_user">Last Name: &ensp; {{user.last_name}}</span>
                <span v-bind:class="{error: lstnmError}" v-if="!edit_user">Last Name: &ensp; {{user.last_name}}<input type="text" name="last_name" id="" v-model="lastName"></span>
            </div>
            <div>
                <span v-if="edit_user">Email: &ensp; {{user.email}}</span>
                <span v-if="!edit_user">Email: &ensp; {{user.email}}</span>
            </div>
            
            <!-- submit and cancel buttons are listed in class "edit_buttons" -->
            <transition name="fade">
                <div v-show="isSure" class="modal_bg" v-on:click="resetisSure">
                    <div class="modal">
                        <div class="modal_text">
                            <p>Are you sure?</p>
                            <div class="modal_buttons">
                                <button type="submit">Submit</button>
                                <button id="cancel_edit" type="button" v-on:click="resetisSure">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            </transition>
        </form>

            <!-- modal pops  -->
            <transition name="fade">
                <div v-show="!isValid" class="modal_bg" v-on:click="resetValid">
                    <div class="modal">
                        <div class="modal_text">
                            <p>Invalid Entry</p>
                        </div>
                    </div>
                </div>
            </transition>
        <!-- all the buttons for this section. Can switch to edit view. In edit view, can submit or cancel. -->
        <div class="edit_buttons">
            <button v-if="edit_user" v-on:click="editUserFunction">Edit</button>
            <button v-if="!edit_user" v-on:click="checkValues">Submit</button>
            <button id="cancel_edit" v-if="!edit_user" v-on:click="editUserFunction">Cancel</button>
        </div>

        <!-- displays all the user's reviews.  -->
        <div v-if="edit_user">
            <hr v-if="edit_user">
            <button v-if="edit_user" v-on:click="displayAdditional" >[[hide]] Reviews</button>
            <div class="additional_content" v-if="hide == 'Hide'">
                {% for review in user.reviews.all %}

                    <!-- allows user to edit or delete their review -->
                    <form action="{% url 'kvetchupapp:edit_review' %}" v-on:keydown.enter.prevent="checkReview" method="post">
                        {% csrf_token %}
                        <div class="review_section">
                            <p class="username">Site: &ensp; {{review.site.name}}</p>
                            <hr>
                            <p v-if="{{review.id}} != reviewNum || isSureDelete" class="review"> {{review.review}}</p>
                            <p v-if="{{review.id}} == reviewNum && !isSureDelete"> <input type="text" name="review" value="{{review.review}}"></p>
                            <p class="date"><i>Date published: &ensp; {{review.review_date}}</i></p>
                            <div class="review_buttons">
                                <div class="edit_buttons" v-if="{{review.id}} != reviewNum || isSureDelete">
                                    <button class="review_edit" type="button" v-on:click="reviewNum = {{review.id}}" >Edit</button>
                                    <button class="delete" type="button" v-on:click="showDeleteModal();reviewNum = {{review.id}}">Delete</button>
                                </div>
                                <div class="review_edit" type="button" v-on:click="checkReview">Submit</button>
                                    <button type="button" class="delete" v-on:click="reviewNum = ''">Cancel</button>
                                </div>
                            </div>
                        </div>
                        <!-- modal to confirm submition -->
                        <transition name="fade">
                            <div v-show="isSureReview" class="modal_bg" v-on:click="resetisSureReview">
                                <div class="modal">
                                    <div class="modal_text">
                                        <p>Submit?</p>
                                        <div class="modal_buttons">
                                            <input type="hidden" v-model="reviewNum" name="review_id">
                                            <button type="submit">Submit</button>
                                            <button id="cancel_edit" type="button" v-on:click="resetisSure">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </transition>
                    </form>
                {% endfor %}
            </div>
        </div>

       


        <form action="{% url 'kvetchupapp:delete_review' %}" method="post">
            {% csrf_token %}
            <transition name="fade">
                <div v-show="isSureDelete" class="modal_bg" v-on:click="resetisSureDelete">
                    <div class="modal">
                        <div class="modal_text">
                            <p>Are you sure?</p>
                            <div class="modal_buttons">
                                <input type="hidden" v-model="reviewNum" name="review_id">
                                <button type="submit">Delete</button>
                                <button id="cancel_edit" type="button" v-on:click="resetisSureDelete(); reviewNum=''">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            </transition>
        </form>

    </div>
</div>

{% endblock %}

kvetchupapp/templates/kvetchupapp/ratings.html
{% extends 'kvetchupapp/base.html' %}

{% block content %}
<div class="content">
    {% if message == 'True' %}
    <transition name="fade">
        <a class="modal_bg" href="{% url 'kvetchupapp:ratings' %}">
            <div class="modal">
                <div class="modal_text">Review Submitted Successfully</div>
            </div>
        </a>
    </transition>
    {% endif %}
    <h2>Reviews</h2>
    <div class="instruction">Please choose corporation to get reviews for. </div>
    <div class="select_section">
        <select v-model="siteId" id="sites_drop_down">
            <option disabled value="Hello" selected>Choose a Site</option>
            {% for site in sites %}
                <option value="{{site.id}}" >{{site.name}}</option>
            {% endfor %}
        </select>
        <button v-on:click="getSiteView" class="rage">Select</button>
    </div>
    <div class="input_section" v-if="name">
        <h3>Name: &ensp; [[name]]</h3>
        
        {% if user.is_authenticated %}
        <form action="{% url 'kvetchupapp:newreview' %}" method="post">
            {% csrf_token %}
            <input type="text" name="review_text" id="" placeholder="Leave a Review!" required>
            <input type="hidden" name="siteId" v-bind:value="siteId">
            <button type="submit">Submit</button>
        </form>
        {% endif %}
        
        {% if user.is_anonymous  %}
        <div class="login_message" v-if="name">
            <span class="login_notice">Please <a class="inline_link" href="{% url 'users:login' %}">log in</a> to leave a review.</span>
        </div>
        {% endif %}
        <br>
        
        
        <div v-if="name && reviews">
            <div v-for="review in reviews">
                <div class="review_section">
                    <p class="username">[[review.user]]</p>
                    <hr>
                    <p class="review"> [[review.review]]</p>
                    <p class="date"><i>Date published: &ensp; [[review.review_date]]</i></p>
                </div>
            </div>
        </div>
        <div class="review_section"  v-if="name && !reviews">
            <p class="username">Be the first to review this site!</p>
        </div>
    </div>
</div>


{% endblock %}